### ISSUE TITLE
Works on stable channel

### ISSUE THREAD

**Issue by gitboss** [artrmz/flutter_control_pad#11]
The code works with stable channel as well by getting the local position using the following code : 
```dart
RenderBox getBox = context.findRenderObject();
getBox.globalToLocal(details.globalPosition))
```
Can you please confirm if the offsets received with the above code are correct?

**Comment by artur-ios-dev** [comment]
Thank you for your feedback. I guess you are right, although there should be a new stable version next week (8. July) so I think it is best to just wait a few more days and all will be good for everyone ^^

**Comment by gitboss** [comment]
I forgot to mention, please use the debouncer class instead of checking for interval by datetime. Currently the IDE shows a warning because the datetime is not immutable. If you like I can provide the code of how is can be implemented..

**Comment by artur-ios-dev** [comment]
@gitboss Sure, go ahead, pull requests are welcome as well.
