### ISSUE TITLE
The joystickInnerPosition will move to the center point

### ISSUE THREAD

**Issue by zhuwei** [artrmz/flutter_control_pad#18]
Hi.
When I call setstate on my StatefulWidget, the joystickInnerPosition of the JoystickView returns to the center point.
```
Timer.periodic(Duration(milliseconds: 500), (as) {
	if (mounted) {
	  setState(() {
		_carState = _carState;
	  });
	}
});
```

**Comment by artur-ios-dev** [comment]
Thank you for your report. I will check it out.

**Comment by zhuwei** [comment]
Please ignore this problem. I should refresh locally

**Comment by pickledgator** [comment]
What was the solution to this? I'm facing a similar behavior.

My reproduction case:
Every time I call `setState((){})` in the parent, while holding the joystick at a deflection, the inner position is reset back to the middle. When an incremental pan is detected, the joystick is immediately deflected again.
