### ISSUE TITLE
more Y stages?

### ISSUE THREAD

**Issue by ElianCodes** [artrmz/flutter_control_pad#20]
Is it possible to create more stages than 0, 0.5, 1.0? I've used this in an app where I'm controlling motors to drive. I would love a function where I can drive my motors faster / slower according to the Y value of the control pad.

Thanks in advance

**Comment by artur-ios-dev** [comment]
@ElianVanCutsem Hello, thank you for your report. IIRC it should return a distance from the center of the joystick normalized to (0.0, 1.0). Are you sure it doesn't return those values? I have just tried it and it seems to work just fine.

```dart
JoystickView(
                  onDirectionChanged: (degrees, distance) {
                    print("$degrees . $distance");
                  },
                )
```

**Comment by ElianCodes** [comment]
Thanks for your answer. I'll check to be sure tomorrow and hit post results here!

**Comment by ElianCodes** [comment]
Hey, Thanks for responding to this issue, It seemed to be an error in my code that rounded it to 0.0, 0.5 or 1.0.
It's solved now, thanks
